### ISSUE TITLE
Adding custom RPC does not work

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2911] opened 2021-06-28 05:07 UTC
I tried with this details below, which works on Metamask:

Fuse Network Details
    "name": "Fuse Mainnet",
    "chainId": 122,
    "shortName": "fuse",
    "chain": "FUSE",
    "network": "mainnet",
    "networkId": 122,
    "nativeCurrency": {"name":"Fuse","symbol":"FUSE","decimals":18},
    "rpc": ["https://rpc.fuse.io"],
    "faucets": [],
    "explorers": [https://explorer.fuse.io/],
    "infoURL": "https://fuse.io/"
 
I got the following error screen.
![image](https://user-images.githubusercontent.com/61957841/123583152-7a766800-d822-11eb-966d-393ea6ec5fc8.png)

**Comment by hboon** [comment] 2021-06-28 05:37
Pending #2912

**Comment by hboon** [comment] 2022-01-02 06:33
@oa-s can you help to follow up on this and see if this is still a problem and how if we can fix this?

**Comment by oa-s** [comment] 2022-01-05 14:06
@hboon i am able to reproduce this issue, but without displaying this alert. I am getting the same error in debug console, but  even with it the chain adds to list.

**Comment by oa-s** [comment] 2022-01-05 14:07
@AW-STJ can u please provide screenshot with filled fields, without alert , to make sure all fields are filled the same as your?

**Comment by hboon** [comment] 2022-01-06 02:53
@oa-s the top comment includes the values filled in (though not a screenshot like you asked for)

**Comment by oa-s** [comment] 2022-01-06 06:22
i filed form according to values on top message, but no error message appeared for me. Just wanted to make sure that app values are right. i will try one more time.

**Comment by oa-s** [comment] 2022-01-06 08:05
@hboon seems like it not replicates for me, i've tried several times, to reproduce it.

**Comment by hboon** [comment] 2022-01-06 11:48
Maybe not an issue anymore because it’s fixed as a side effect. If you conclude it’s not a problem anymore, you can close it

**Closed** 2022-01-06 11:49 UTC
Labels: Bug
