### ISSUE TITLE
Upgrade to send transactions with EIP-1559 protocol

### ISSUE THREAD

**Issue by beckyzhang** [AlphaWallet/alpha-wallet-ios#5733] opened 2022-11-03 02:36 UTC
name: Upgrade to send transactions with EIP-1559 protocol
about: Using AlphaWallet to send transactions with EIP-1559 protocol

---

**Describe my question**
Can we modify the project code to support sending transactions with EIP-1559 protocol? Or, it will upgrade and when is it?

**Comment by hboon** [comment] 2022-11-03 13:38
Thanks for the interest. There's issue #4138 and a PR which is WIP at #5172 for adding EIP-1559. Closing this as duplicate of #4138

**Closed by hboon** 2022-11-03 13:38 UTC
