### ISSUE TITLE
Text field (amount) periodically cleared whilst typing

### ISSUE THREAD

**Issue by jzaki** [AlphaWallet/alpha-wallet-ios#1681] opened 2020-01-30 05:16 UTC
- Click on currency/token (Tested with ETH mainnet and rinkeby)
- click Send action
- scan address, address populated
- amount is 0, enter new amount (eg .09)
- after a few seconds, amount goes back to 0. Expect: typed amount to remain.

**Comment by hboon** [comment] 2020-01-30 10:37
@jzaki I thought it might be triggered when the price refreshes but I can't reproduce on mainnet (both Ether and ERC20) and Rinkeby. Can you try to reproduce it with ETH mainnet, sending Ether and let me know the exact amount you typed? And whether it's set to ETH or USD?

**Comment by jzaki** [comment] 2020-02-05 06:06
@hboon more details...
iPhone5S, iOS 12.4.3, AW Ver 2.20 (320), TS 2019/10
- Click on ETH mainnet
- click Send action
- amount is 0, enter new amount (eg .08). Value remains unchanged as expected.
- scan address, address populated. Value clears to 0. Expect: value remains the same.
- enter new amount (eg .08)
- after a few seconds, amount goes back to 0. Expect: typed amount to remain.

**Comment by hboon** [comment] 2020-02-12 06:06
Verify this is fixed too: https://github.com/AlphaWallet/alpha-wallet-ios/pull/1697#issuecomment-584891723

**Comment by hboon** [comment] 2020-05-14 09:07
@nimitparekh2020 can you help to verify if this is fixed in `master` already?

**Comment by nimitparekh2020** [comment] 2020-05-14 09:37
Let me check it and update you.

**Comment by hboon** [comment] 2020-05-26 12:50
@vladyslav-iosdev can you help to verify? I think there's a good chance this is already fixed.

**Comment by vladyslav-iosdev** [comment] 2020-05-26 14:09
@hboon seems like this doesn't appear, but i found other other issue:

- click on ETH mainnet
- click Send action
- set amount to 1,
- press ETH float button to convert to USD
- scan address, address populated, textfield value changed from USD to ETH.

**Comment by vladyslav-iosdev** [comment] 2020-05-29 08:20
> @hboon seems like this doesn't appear, but i found other other issue:
> 
> * click on ETH mainnet
> * click Send action
> * set amount to 1,
> * press ETH float button to convert to USD
> * scan address, address populated, textfield value changed from USD to ETH.

@hboon Do i need to fix this, or its expacted behaviour?

**Comment by hboon** [comment] 2020-05-29 08:36
@vladyslav-iosdev sounds like a bug. Can you create an issue and fix it? Take care that it should remain as ETH (or switch to ETH if it is USD) if an amount is included in the EIP681 link.

Close this issue and link to that new issue from here.

**Closed** 2020-05-29 08:38 UTC
Labels: bug
