### ISSUE TITLE
The transection record, balance, balance in TokenScript action card are not synced 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1362] opened 2019-08-21 02:57 UTC
![D26E99D4-CB75-4AC4-8476-6442D5908319](https://user-images.githubusercontent.com/33795543/63399186-62518880-c402-11e9-943c-0b57b25da427.jpeg)
![CDA5BCD7-99E8-4561-A843-F8C3CAA9689D](https://user-images.githubusercontent.com/33795543/63399187-62518880-c402-11e9-84cd-038b995e2e38.jpeg)
![EC5B5542-796D-4EB5-AA32-F01A6644F87A](https://user-images.githubusercontent.com/33795543/63399188-62ea1f00-c402-11e9-9af5-f0832cf8f17f.jpeg)
![C6517194-CE59-4B35-B5E6-D85E4748A143](https://user-images.githubusercontent.com/33795543/63399189-6382b580-c402-11e9-9067-4872e4c052f6.jpeg)

**Comment by hboon** [comment] 2019-09-05 07:10
@James-Sangalli is this fixed with #1420 ?

**Comment by zhangzhongnan928** [comment] 2019-09-05 07:29
I guess this requires the integration with services like AmberData?  

		
Victor Zhang
CEO, AlphaWallet
							
Not only display information, @Alpha_Wallet let you preform the functions: DEPOSIT, WITHDRAW, PAYBACK, GENERATE, MO… https://t.co/6dJfdvnM3i

**Comment by hboon** [comment] 2019-09-05 07:35
@zhangzhongnan928 ultimately yes, services like AmberData will help us to know that balances has changed and let us refresh it efficiently and quickly.

But even without AmberData, after the balance has changed for a while, and we visit this screen again, the app should be able to refresh it itself and get the correct balance. #1420 fixed an issue where we keep the old value of balances around and don't fetch the updated balances. So it might fix this issue to a certain extent (as long as we get the values all from the same node).

**Comment by zhangzhongnan928** [comment] 2019-09-05 08:09
Not updated fast is ok, but need to be synced. 
Cannot updated in one place, but not updated in others. 


		
Victor Zhang
CEO, AlphaWallet
							
Not only display information, @Alpha_Wallet let you preform the functions: DEPOSIT, WITHDRAW, PAYBACK, GENERATE, MO… https://t.co/6dJfdvnM3i

**Comment by hboon** [comment] 2019-09-05 08:13
> Not updated fast is ok, but need to be synced. Cannot updated in one place, but not updated in others

Right. We should at least fix this in this issue.

**Comment by James-Sangalli** [comment] 2019-09-05 10:02
@zhangzhongnan928 use the latest build from testflight, it updates the cards on each click.

**Comment by James-Sangalli** [comment] 2020-02-07 01:23
I believe this was fixed with the cache PR, not able to reproduce anymore as the values are given in real time from the TokenScript

**Closed by James-Sangalli** 2020-02-07 01:23 UTC
Labels: bug
