### ISSUE TITLE
Make Travis tests use keys set in Travis dashboard

### ISSUE THREAD

**Issue by oa-s** [AlphaWallet/alpha-wallet-ios#6112] opened 2023-01-10 09:28 UTC
@hboon can u please create a new infura key and make it being used only for tests purposes, or just share a key with me and i will do the rest

**Comment by hboon** [comment] 2023-01-10 09:41
We can't create new test keys and use them because forks would use it too and they'll be public and be rate limited soon.

So it's better to fix it so that we can get Travis to use the one we tell it to. There are 3 things to do:

A. Travis supports setting environment variables, some of the previous changes (including support for `.credentials`) was partly to support reading from environment variables. But the problem is Travis inject the environment variables to the build process not into the app's process. So the easiest way, I think, is to modify AlphaWallet so the keys are read from the app's `Info.plist` (have to be careful if extensions are affected). We can change `Constants+Credentials.swift`'s properties to read it from `Info.plist` if they are available (first environment variables, then `Info.plist`, then finally the hardcoded values?)'
B. And add Run Script Phase when we build for testing to read from environment variables (which we can inject into Travis using their website) and update Info.plist?
C. We'll have to push PRs to https://github.com/AlphaWallet/alpha-wallet-ios instead of your own fork because we can only inject environment variables for PRS in the original repo, not for repo forks (otherwise other people can steal the keys)

And alternative to A+B is if there's a way to read environment variables for the build process and inject into the app's process when starting up. That would be better and much easier.

Does these make sense?

**Comment by hboon** [comment] 2023-01-10 09:43
> And alternative to A+B is if there's a way to read environment variables for the build process and inject into the app's process when starting up. That would be better and much easier.

Actually, maybe we can do this within `.travis.yml`?

**Comment by eviltofu** [comment] 2023-01-10 10:26
https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings

**Comment by eviltofu** [comment] 2023-01-10 10:33
https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings

> Variables defined in repository settings are the same for all builds, and when you restart an old build, it uses the latest 
> values. These variables are not automatically available to forks.

Won't this cause a problem?

> Similarly, we do not provide these values to untrusted builds, triggered by pull requests from another repository.

**Comment by eviltofu** [comment] 2023-01-10 11:18
What is the Infura key used for in the Travis tests?

**Comment by hboon** [comment] 2023-01-10 12:08
>>  These variables are not automatically available to forks.

> Won't this cause a problem?

It's already addressed in the first comment. Refer to (C)

> What is the Infura key used for in the Travis tests?

The ones we inject is our production key. But it isn't used, as described in the first comment

**Closed** 2023-01-12 00:53 UTC
