### ISSUE TITLE
binance signtransaction error ios 17

### ISSUE THREAD

**Issue by akhilccrb** [AlphaWallet/alpha-wallet-ios#7008] opened 2023-10-04 07:43 UTC
In browser section while interacts to smart contract signing transaction fail. But it works in ios 17 lower versions, in BNB Chain.

**Comment by akhilccrb** [comment] 2023-10-05 06:35
https://bsc-dataseed.binance.org  - Request timeout error only in ios 17 devices.





convertToUserFriendlyError URL: https://bsc-dataseed.binance.org error: connectionError(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x10951cad0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <9A26F30F-242E-4051-BB66-A63EA51E6236>.<565>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <9A26F30F-242E-4051-BB66-A63EA51E6236>.<565>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://bsc-dataseed.binance.org/, NSErrorFailingURLKey=https://bsc-dataseed.binance.org/, _kCFStreamErrorDomainKey=4})

**Comment by akhilccrb** [comment] 2023-10-09 09:30
signedTransaction: "0xf8cb30850218711a00830134ce946a6118ea4ff6792c6e6ecc50dfb6282801845ae880b864969e3756000000000000000000000000b59f91ee125d1ab802444e57fb50131ffe9cc6dd00000000000000000000000055d398326f99059ff775485246999027b31979550000000000000000000000000000000000000000000000008ac7230489e800008194a06932f8c2857fc6ec29e4defc1c88a28e62bc8b8d7d5054d6704d9e7934ef16b6a06932f8c2857fc6ec29e4defc1c88a28e62bc8b8d7d5054d6704d9e7934ef16b6"


After creating  signedTransaction from address is different. This is the reason for the issue. I think its signing error. but it is happening only device above ios 17.  @hboon

**Comment by hboon** [comment] 2023-10-17 04:18
Duplicate of #7020

**Closed by hboon** 2023-10-17 04:18 UTC
