### ISSUE TITLE
Can’t Send Tokens 

### ISSUE THREAD

**Issue by Librechain** [AlphaWallet/alpha-wallet-ios#7096] opened 2024-01-25 00:37 UTC
Clicking on a token in the wallet interface takes user to a blank screen where the options are nulled out entirely. It’s a hit or miss whether the correct options (send or activity) will pop up with populated spaces. Makes the wallet borderline unusable at times. Please fix.

**Comment by Librechain** [comment] 2024-01-25 00:42
https://github.com/AlphaWallet/alpha-wallet-ios/assets/59129716/a248851b-7fe6-474d-8100-b05307fddff5

Here’s a video where I reproduce the issue in question. Again. It’s hit or miss whether the correct interface for sending the token actually appears. Sometimes I’m forced to enter this loop 10+ times before the correct interface shows. Please fix.

**Comment by medeirosfalante2** [comment] 2024-04-04 14:25
I have a same issue https://github.com/AlphaWallet/alpha-wallet-ios/issues/7107

**Comment by hboon** [comment] 2024-04-05 04:16
Aware of this one. Will hunt it down. Thanks.

**Comment by hboon** [comment] 2024-05-29 06:43
Duplicate of #7107. Fixed

**Closed by hboon** 2024-05-29 06:43 UTC
