### ISSUE TITLE
Error sending PHI20 tokens causing to go to contract address rather than destination wallet 

### ISSUE THREAD

**Issue by Phinetwork** [AlphaWallet/alpha-wallet-ios#5810] opened 2022-11-16 21:37 UTC
Phi20 tokens are not sending to the wallet address it seems to be sending to the contract address not sure why this is happening. Was working fine before this is a major problem as when users are sending phi20 tokens they are Being lost because they are going to the contract address and not the wallet address user is sending to.

It's only like that on the newest update i don't know why when send phi20 token it is sending to the contract address of the token rather then the destination wallet. Only happening on newest update of alpha wallet please need this fixed asap @hboon

**Comment by Phinetwork** [comment] 2022-11-16 21:45
Yes i can confirm it is on the newest update just updated a new device after a successful phi20 transaction to the newest update and it's causing All phi20 transactions to go to the contract address rather than the destination wallet address is this very important to fix. Please if we can get to this as soon as possible so users don't loose funds. Thanks you

**Comment by Phinetwork** [comment] 2022-11-16 21:53
Can see when sending 10 Usdc it went to contract address instead of the address added to the receipt. https://phiscan.com/tx/0x31c0710064803618c09f38e1039bc41ff1da9175832dbe00b794d4fad0afec8a

**Comment by hboon** [comment] 2022-11-17 01:20
Thanks for reporting. We fix this in #5812

**Comment by hboon** [comment] 2022-11-17 01:20
Duplicate of #5811

**Closed by hboon** 2022-11-17 01:20 UTC

**Comment by Phinetwork** [comment] 2022-11-17 03:03
Why is app not in App Store says not available in country or region. Can you please check this

**Comment by hboon** [comment] 2022-11-17 03:11
@Phinetwork took it down until the hotfix is approved by Apple

**Comment by Phinetwork** [comment] 2022-11-17 03:19
> @Phinetwork took it down until the hotfix is approved by Apple

Ok thank you for update. How long before you think the hot fix is approved by apple. Appreciate you getting to this so quickly.

**Comment by hboon** [comment] 2022-11-17 03:27
@Phinetwork usually a few hours to a day

**Comment by Phinetwork** [comment] 2022-11-17 03:32
> @Phinetwork usually a few hours to a day

Ok great thank you 🙏
