### ISSUE TITLE
WalletConnect keeps loading when connecting to a DApp.

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#2744] opened 2021-05-10 00:52 UTC
WalletConnect keeps loading when connecting to a DApp.
Only A refresh of the dapp website and a restart of AlphaWallet will solve it.

**Comment by hboon** [comment] 2021-05-10 01:13
@zhangzhongnan928 this is with dapps that usually work with WalletConnect + AlphaWallet, right?

**Comment by hboon** [comment] 2021-12-07 15:45
Duplicate of #3275

**Closed by hboon** 2021-12-07 15:45 UTC
Labels: Bug
