### ISSUE TITLE
Improve Segmented Controls and Token Groups

### ISSUE THREAD

**Issue by colourfreak** [AlphaWallet/alpha-wallet-ios#3546] opened 2021-12-14 15:50 UTC
Another issue related to the Wallet tab. We are very, very close to the end design I made while designing Samoa.
So based on Hu's recent work, we now have specified token groups. 

- All (Assets, Defi, Governance but no Collectibles)
- Assets (ERC20)
- Collectibles (ERC721 and ERC1155), 
- DeFi (all ctokens, atokens, ptokens, itokens, liquidity pools, etc...), 
- Governance (DAO tokens like COMP, UNI, etc)

**So we have to:**
1. Update Segmented Controls (so they are horizontally scrollable) - ScrollableSegmentedControl
2. Add Token groups

**Zeplin:**
https://zpl.io/bAgG6ox

**Prototype**
https://invis.io/6U125DXFWE2X

<img width="1683" alt="Screenshot 2021-12-14 at 16 50 01" src="https://user-images.githubusercontent.com/51817359/146032038-baaa2a4d-823d-4fd9-a708-589cffa6e022.png">

![Wallet_Long](https://user-images.githubusercontent.com/51817359/146029729-ecb4e36a-0c46-495b-a2f1-8529f38309ca.jpg)

**Comment by colourfreak** [comment] 2021-12-14 15:56
Examples of scrollablesegmentedcontrol

https://user-images.githubusercontent.com/51817359/146033231-15e38a17-c863-491b-98f8-b530b9993589.MOV

https://user-images.githubusercontent.com/51817359/146033184-487ae25c-5157-4e0b-b900-4a7d6396db63.MOV

**Comment by JamesSmartCell** [comment] 2021-12-14 22:43
@hboon We need to come up with a way to distinguish these tokens - I don't know of any way to tell from looking at the token, but maybe an API can say? Failing this we should maintain a common list of tokens that are governance or defi.

**Comment by hboon** [comment] 2021-12-15 02:40
> We need to come up with a way to distinguish these tokens - I don't know of any way to tell from looking at the token, but maybe an API can say? Failing this we should maintain a common list of tokens that are governance or defi.

@JamesSmartCell It's already in the token mapping schema, but the data hasn't been populated yet: https://github.com/AlphaWallet/tokens/blob/main/tokens.json, eg.

```
[
  {
    "contracts": [
      {"address": "0xc18360217d8f7ab5e7c516566761ea12ce7f9d72", "chainId": 1},
      {"address": "0xbD7A5Cf51d22930B8B3Df6d834F9BCEf90EE7c4f", "chainId": 137},
      {
        "address": "0xfeA31d704DEb0975dA8e77Bf13E04239e70d7c28",
        "chainId": 42161
      },
      {"address": "0x65559aA14915a70190438eF90104769e5E890A00", "chainId": 10}
    ],
    "group": "Governance"
  },
  {
    "contracts": [
        //…
    ],
    "group": "Governance"
  },
  //…
```

So how to group them should be done #3549

**Comment by colourfreak** [comment] 2022-04-15 11:54
What is the plan to release this? It's live and working on Android.

**Comment by hboon** [comment] 2022-04-18 03:45
@colourfreak It's merged recently. So will be in the next release.

**Comment by hboon** [comment] 2022-04-28 04:08
Done earlier

**Comment by colourfreak** [comment] 2022-04-28 12:39
The problem is - these groups are empty. 
![2022-04-28 14 37 56](https://user-images.githubusercontent.com/51817359/165753750-bcaac40a-2b1f-46ab-92c0-927bb1dece73.png)
![2022-04-28 14 37 58](https://user-images.githubusercontent.com/51817359/165753759-ad38f4c3-6f91-4042-b876-60ae4cf1f3e8.png)

Compare this with Android
![2022-04-28 14 38 17](https://user-images.githubusercontent.com/51817359/165753796-59e4db73-ccc2-450f-b2b6-a97f10a5c1aa.jpg)
![2022-04-28 14 38 14](https://user-images.githubusercontent.com/51817359/165753788-f648e4de-8e16-44fc-b77e-747021110795.jpg)

**Comment by hboon** [comment] 2022-04-28 14:49
The code is working properly for iOS. It's actually a bug on Android's side, or at least not by design.

If you add this token `0x21bfbda47a0b4b5b1248c767ee49f7caa9b23697` on Ethereum mainnet, you'll see it appear under Governance like this:

<img width="487" alt="Screenshot 2022-04-28 at 10 43 03 PM" src="https://user-images.githubusercontent.com/56189/165778970-ffe6bfb1-50c2-4692-804a-ec2dff53a80b.png">

The reason why it's not appearing on iOS is because the filtered down `tokens.json` (that Android should be using, but isn't. Instead it's usually the original, bigger file but with erroneous mapping) has a much smaller subset of the original. So we should fix it there. We had to filter it down earlier because the mapping isn't accurate (and we can't put wrong mappings in as that will affect the price, display, or in the worse case cause the users to lose funds). But I think what we can do is to add back the tokens that are on mainnet and not map those to other chains.

Once I have the updated `tokens.json` file, I'll create an issue for Android to update.

Leaving this issue open until I create an updated file and issue for Android

- [ ] Create updated `tokens.json`
- [ ] Create Android issue

**Comment by hboon** [comment] 2022-04-29 04:03
Closing. Will see results in next build

**Closed by hboon** 2022-04-29 04:03 UTC
