### ISSUE TITLE
1 QR scan button for all

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#1214] opened 2019-05-08 10:43 UTC
![IMG_4791](https://user-images.githubusercontent.com/33795543/57369391-ff741280-71bf-11e9-86f3-e05ce1599308.PNG)

Make all the QR Scan buttons in AlphaWallet with multi-functions, the same button for:
1. wallet/contract address, Ask user want to transfer or add a new contract
2. EIP67 681 831 URL/URI, go to transfer flow
3. MagicLink, go to MagicLink flow
5. normal URL, open in DApp Browser 

Currently, there are 3 ways to open QR Scanner:
1. The + button in wallet page
2. The camera button in send page
3. The text button in DApp Browser

**Comment by JamesSmartCell** [comment] 2019-10-31 07:14
I like this, but have a dedicated icon next to the '+', something like [+] turned 90 degrees which you see as a standard scan icon. Then do a response as detailed above.

**Comment by tomekalphawallet** [comment] 2019-11-05 08:26
What about this?

![Screenshot 2019-11-05 09 25 13](https://user-images.githubusercontent.com/51817359/68190743-434ca680-ffae-11e9-8da3-dfbda8f12de7.png)

![Screenshot 2019-11-05 08 49 51](https://user-images.githubusercontent.com/51817359/68190662-18625280-ffae-11e9-99aa-a6da311204dd.png)

**Comment by hboon** [comment] 2019-11-05 08:32
Shall we start a new thread in the forum and come back after we finalise it?

(I think James Brown commented that users don't understand what the QR code icon means, which is why we switched to the camera).

**Comment by tomekalphawallet** [comment] 2019-11-05 08:34
Yes, good idea.

**Comment by JamesSmartCell** [comment] 2019-11-05 23:09
This looks good. Do you think the icons stand out more in that 'holo' colour or have them as standard 'light' mode which is dark grey.

**Comment by jzaki** [comment] 2020-02-18 04:43
![](https://github.trello.services/images/mini-trello-icon.png) [As a user engaging with other wallets/services, I want to quickly access a QR code scanner, so that I can conduct business more readily/intuitively.](https://trello.com/c/ARJaAPne/128-as-a-user-engaging-with-other-wallets-services-i-want-to-quickly-access-a-qr-code-scanner-so-that-i-can-conduct-business-more-re)

**Comment by James-Sangalli** [comment] 2020-06-24 06:44
Duplicate of #1723

**Closed by James-Sangalli** 2020-06-24 06:44 UTC
Labels: enhancement
