### ISSUE TITLE
Integration Docs Here:

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/alpha-wallet-ios#2412] opened 2020-12-26 10:08 UTC
Integration Docs Here:

https://docs.hecochain.com/#/en-us/wallet

Thanks a lot.

[Heco icon.zip](https://github.com/AlphaWallet/alpha-wallet-android/files/5742914/Heco.icon.zip)

__Originally posted by @kevinho in https://github.com/AlphaWallet/alpha-wallet-android/issues/1702__

**Comment by hboon** [comment] 2021-01-05 14:08
Duplicate of #2411

**Closed by hboon** 2021-01-05 14:08 UTC
