### ISSUE TITLE
LP creation screen displays as media on lockscreen on iOS

### ISSUE THREAD

**Issue by hieronymus4826** [AlphaWallet/alpha-wallet-ios#2991] opened 2021-07-26 16:59 UTC
While creating an LP on Polycrystal, the screen locked and got this:

![IMG-3853.jpg](https://user-images.githubusercontent.com/84448420/127028708-b331f2ce-499b-4c0c-b143-507d0a59f9ac.jpg)

Probably low priority, but checking if it might affect other things.

**Comment by hboon** [comment] 2021-08-03 08:54
@hieronymus4826 interesting! Can you describe, step by step how you get here? I can't get past the connect options in https://polycrystal.finance/ with the dapp browser.

**Comment by hieronymus4826** [comment] 2021-08-03 21:42
I have no problem connecting when I press the MetaMask button. 

Then I go to Trade -> Liquidity (at this point I get disconnected from the wallet as we are moving to "dex,polycrystal.finance") - > I recconect and approve the pair

![Polycrystal_2](https://user-images.githubusercontent.com/84448420/128090145-c00bcad2-0daf-4f86-968f-e5a84821895b.JPG)

And when I am this confirmation screen to supply liquidity and lock the screen I get:

![Polycrystal](https://user-images.githubusercontent.com/84448420/128090192-de9639aa-196e-4733-888b-5c9d5a5f8536.JPG)

**Comment by hboon** [comment] 2021-08-05 05:03
Strange indeed! I can make it happen once and then I can't reproduce it anymore. I *guess* it's because the site is playing an audio stream or something which causes iOS to display that media overlay, but I can't reproduce it anymore to examine it. But doesn't seem like it's something we need to fix or can fix at the moment. Closing for now. But don't let this stop you from reporting issues. They are really helpful!

**Closed by hboon** 2021-08-05 05:03 UTC
