### ISSUE TITLE
Failed transactions transaction looks like successful transactions

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-ios#2252] opened 2020-11-08 12:48 UTC
Looks like the failed status for Eth transactions are not captured correctly. 

Screen recording: https://drive.google.com/file/d/1fB-p6VUpDZwk8G2riIgYDo86xWcRXigF/view?usp=sharing

Designs: https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5e5396f1b3fc047479f08600

Wallet: 0xfCABe3451aC8EDfB8FB6b9274C2E095D9cCC8082

**Comment by hboon** [comment] 2020-11-09 03:24
@AW-STJ Generally, would you provide screenshot(s) instead of a video? It's much easier and faster to interpret unless the sequence of action is really important. And it's more likely to (uploaded) file will stick around.

And in this case, would you paste the transaction hash too? (the Ethereum account is helpful, thanks)

**Comment by hboon** [comment] 2020-11-09 07:33
I can reproduce this though. So don't worry about it.

**Comment by hboon** [comment] 2020-11-09 07:44
Duplicate of #2238

**Closed** 2020-11-12 08:43 UTC
Labels: bug
